name: Build and Publish

on:
  push:
    branches: [ main ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Publish to s3
        env:
          PUBLISH_S3_BUCKET: bitovi-operations-tgif-sites
        run: |
          echo "running scripts/ci/publish.sh"
          ./scripts/ci/publish.sh

  # https://github.com/bitovi/github-actions-bitops-ci-cd
  deploy-demo:
    # only deploy if not pull request
    if: github.event_name != 'pull_request'
    needs: [ publish ]
    runs-on: ubuntu-latest
    steps:
    - name: Deploy Stage
      uses: bitovi/github-actions-bitops-ci-cd@0.5.0
      with:
        github-token: ${{ secrets.OPERATIONS_REPO_TOKEN }}
        org: bitovi
        repo: operations-tgif
        branch: main
        workflow: deploy-demo-trigger.yaml